In [1]:
import polars as pl
import glob

In [2]:
train_files = sorted(glob.glob('../data/train_part_*.parquet'))

operations = pl.scan_parquet(train_files)
labels = pl.scan_parquet('../data/train_labels.parquet')

operations = operations.with_columns(
    pl.col('event_dttm').str.to_datetime(),
    pl.col('event_type_nm').cast(pl.Int8, strict=False),
    pl.col('event_desc').cast(pl.Int16, strict=False),
    pl.col('channel_indicator_type').cast(pl.Int8, strict=False),
    pl.col('channel_indicator_sub_type').cast(pl.Int16, strict=False),
    pl.col('operaton_amt').cast(pl.Float32, strict=False),
    pl.col('currency_iso_cd').cast(pl.Int16, strict=False),
    pl.col('pos_cd').cast(pl.Int16, strict=False),
    pl.col('timezone').cast(pl.Int16, strict=False),
    pl.col('operating_system_type').cast(pl.Int8, strict=False),
    pl.col('developer_tools').cast(pl.Int8, strict=False),
    pl.col('phone_voip_call_state').cast(pl.Int8, strict=False),
    pl.col('web_rdp_connection').cast(pl.Int8, strict=False),
    pl.col('battery').str.replace('%', '').cast(pl.Int8, strict=False),
    pl.col('mcc_code').cast(pl.Int8, strict=False),
    pl.col('screen_size').str.split_exact('x', 1)
    .struct.rename_fields(['screen_w', 'screen_h'])
    .alias('screen_dims')
)

operations = operations.with_columns(
    pl.col('event_dttm').dt.date().alias('event_date')
).unnest('screen_dims').with_columns(
    pl.col('screen_w').cast(pl.Int16, strict=False),
    pl.col('screen_h').cast(pl.Int16, strict=False)
)
operations = operations.drop(['accept_language', 'browser_language', 'screen_size', 'device_system_version'])


labels = labels.with_columns(
    pl.col('target').cast(pl.Int8)
)

df = operations.join(labels, on=['customer_id', 'event_id'], how='left')
df = df.with_columns(pl.col('target').fill_null(0))

In [3]:
df.head().collect()

shape: (5, 23)
┌────────────┬────────────┬────────────┬────────────┬───┬──────────┬──────────┬───────────┬────────┐
│ customer_i ┆ event_id   ┆ event_dttm ┆ event_type ┆ … ┆ screen_w ┆ screen_h ┆ event_dat ┆ target │
│ d          ┆ ---        ┆ ---        ┆ _nm        ┆   ┆ ---      ┆ ---      ┆ e         ┆ ---    │
│ ---        ┆ i64        ┆ datetime[μ ┆ ---        ┆   ┆ i16      ┆ i16      ┆ ---       ┆ i8     │
│ i64        ┆            ┆ s]         ┆ i8         ┆   ┆          ┆          ┆ date      ┆        │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════════╪══════════╪═══════════╪════════╡
│ 1231231231 ┆ 1239993003 ┆ 2024-10-01 ┆ 14         ┆ … ┆ null     ┆ null     ┆ 2024-10-0 ┆ 0      │
│ 23129      ┆ 82879      ┆ 05:29:14   ┆            ┆   ┆          ┆          ┆ 1         ┆        │
│ 1231231231 ┆ 1245318757 ┆ 2024-10-01 ┆ 7          ┆ … ┆ null     ┆ null     ┆ 2024-10-0 ┆ 0      │
│ 23129      ┆ 13936      ┆ 10:17:22   ┆            ┆   ┆          ┆          ┆ 1         ┆        │
│ 1231231231 ┆ 1233292855 ┆ 2024-10-01 ┆ 3          ┆ … ┆ null     ┆ null     ┆ 2024-10-0 ┆ 0      │
│ 23129      ┆ 80171      ┆ 10:20:03   ┆            ┆   ┆          ┆          ┆ 1         ┆        │
│ 1231231231 ┆ 1243343054 ┆ 2024-10-02 ┆ 14         ┆ … ┆ null     ┆ null     ┆ 2024-10-0 ┆ 0      │
│ 23129      ┆ 30665      ┆ 07:48:09   ┆            ┆   ┆          ┆          ┆ 2         ┆        │
│ 1231231231 ┆ 1262155011 ┆ 2024-10-02 ┆ 14         ┆ … ┆ null     ┆ null     ┆ 2024-10-0 ┆ 0      │
│ 23129      ┆ 46513      ┆ 11:20:40   ┆            ┆   ┆          ┆          ┆ 2         ┆        │
└────────────┴────────────┴────────────┴────────────┴───┴──────────┴──────────┴───────────┴────────┘

In [6]:
df.collect().shape

(85677840, 23)

In [3]:
df.select(pl.col('target').value_counts()).collect()

shape: (2, 1)
┌──────────────┐
│ target       │
│ ---          │
│ struct[2]    │
╞══════════════╡
│ {0,85626402} │
│ {1,51438}    │
└──────────────┘

In [4]:
df.collect_schema()
df.collect().n_unique('customer_id')

100000

In [5]:
df.collect().estimated_size('mb')

5327.564253807068

In [8]:
df.sink_parquet('../data/train_full.parquet')